### ISSUE TITLE
bookmark thumbnails 

### ISSUE THREAD

**Issue by QueenHarmony** [rtm516/Bookmark-Manager#1]
like the pictures you showcase are...well showcasing, the manager used to be able to give you the choice to pick and choose any image in the current URL you are bookmarking, as a thumbnail in said bookmark, to me, this was one of, if not the most important feature, the UI is something i like because i got used to it, but thumbnails showing you exactly what each bookmark is by a picture you picked for it, is a massive help to people like i, who posses literal thousands of bookmarks, besides the vanity of having something akin to an image gallery in your bookmarks, like i mentioned already, i consider it extremely useful, organisation, easy tracking of older bookmarks, and overall visual appeal, and would be greatly thankful is such a feature could be brought back

**Comment by rtm516** [comment]
What exactly do you mean? As the images on my bookmarks work fine.

**Comment by QueenHarmony** [comment]
I mean exactly that, they dont work for me, im not sure how they are for you, and also i know of at least one other person who's bookmark images are not working, he said so on the google blog thing, you posted on, the only solution we have is turning the bookmark file read only which is not ideal as older bookmarks can not be removed or edited, from what i know, you said this is exactly how the app was beafore the "discontinued" update, and the images would not be working then either

**Comment by rtm516** [comment]
![2018-09-12_12-13-00](https://user-images.githubusercontent.com/5401186/45421539-44719480-b685-11e8-864c-13e8e1f249b0.png)
![2018-09-12_12-13-17](https://user-images.githubusercontent.com/5401186/45421542-45a2c180-b685-11e8-9b62-f73a86db48d7.png)
Working fine as you can see for me

**Comment by QueenHarmony** [comment]
yes, i know, you said that already, but its not for me, and i don't know why that is this way

**Comment by QueenHarmony** [comment]
can i ask what version of chrome you are using, also, is there a way to downgrade to that version without being constantly logged off, as i have tried downgrading chrome in the past and it seems to log me off everything, and trying to log back in only work as long as i don't close chrome

**Comment by rtm516** [comment]
Im on chrome Version 69.0.3497.100 (Official Build) (64-bit)

**Comment by QueenHarmony** [comment]
huh..ok, so you are on almost the latest version and the images are working fine for you, then what am i doing wrong here, im no expert in this sort of stuff so im sure im missing something

**Comment by jaakon** [comment]
I have/had the same issue, but I think I can help: The images are not added to already existing bookmarks but instead are only generated when you add a new bookmark.

At least this is the behaviour for me.

**Comment by QueenHarmony** [comment]
huh, if that is the case i may have to review every single one of my bookmarks and re-bookmark them, which would be...interesting to go trough, i doubt exporting and importing them again would help though if im going to go trough all this its worth a shot i suppose, still, i suppose its something, thank you, ill give this a try and i suppose ill report back what i see

**Comment by QueenHarmony** [comment]
so, i made a copy of my bookmark file just in case, left the copy somewhere, removed the original's read only tag, went in, made a new bookmark, two actually, and neither managed to retain the images upon closing and re-opening google

**Comment by QueenHarmony** [comment]
one thing i could do is revert back to a fairly old version of chrome, might be over a year old, which would fix it since that version never had issues to begin with, besides youtube bookmarks but one site over millions is not a problem, what is a problem though is that if i revert back too much it logs me off all accounts and if i close chrome it logs me off any ones i log back in, considering i work using some of those accounts its not exactly ideal to have this

EDIT : to be more specific, i believe it logs me off my google account which in turn houses my other accounts around the web

EDIT 2 : while writing this i also thought of this, my external hard drive that i keep for backup purposes, was made using my old laptop's remains, and i believe it likely houses my google files as they where the moment that laptop stopped working, which was nearly a year or maybe more before this whole issue with the manager being discontinued, not sure if that helps, but i figured i would mention it

**Comment by rtm516** [comment]
I did not find a solution to this issue but I have started a rewrite to this extension if you would like to contribute or test it please check out the rebuild branch. https://github.com/rtm516/Bookmark-Manager/tree/rebuild
