### ISSUE TITLE
Unobfuscated version

### ISSUE THREAD

**Issue by chm-dev** [rtm516/Bookmark-Manager#3]
Do you happen to know if there is unobfuscated version of this extension?
I'd love to try to bring it back to live with some extra features.

**Comment by rtm516** [comment]
Not publicly available. When I set this up I looked for one, all I found was that they most likely used closure to minify it but without a lot of work then it will stay like this. Here is googles public closure compiler [google/closure-compiler-js](https://github.com/google/closure-compiler-js).

**Comment by rtm516** [comment]
If you want to have a go at making it readable I'm more than happy for you to make pull requests if you get anywhere.

**Comment by chm-dev** [comment]
I think it is not worth tbh. It is such a mind bender. Even after putting it through pretty print etc. I think I'll just try to rebuild the core mechanics in vue and make it new extension similar to what this is but whith proper screenshots and reader view.

**Comment by NaturalHarmonia** [comment]
> I think it is not worth tbh. It is such a mind bender. Even after putting it through pretty print etc. I think I'll just try to rebuild the core mechanics in vue and make it new extension similar to what this is but whith proper screenshots and reader view.

I look forward to that.

**Comment by rtm516** [comment]
I have started a rewrite to this extension if you would like to contribute or test it please check out the rebuild branch. https://github.com/rtm516/Bookmark-Manager/tree/rebuild
