### ISSUE TITLE
Unrecognized property 'bookmarks_ui' of manifest key 'chrome_ui_overrides'.

### ISSUE THREAD

**Issue by NaturalHarmonia** [rtm516/Bookmark-Manager#4]
`   "background": {
      "persistent": true,
      "scripts": [ "bootstrap.js", "background_compiled.js" ]
   },`

I'm not techsavvy. Could anyone help me with this problem I'm having? I followed the instructions and installed the extension but I'm getting this error. Also when I go to bookmarks with the extension installed I get ERR_BLOCKED_BY_CLIENT.

**Comment by rtm516** [comment]
The first issue can be ignored, chrome is just lying to you as it still works. The second may be some form of adblocker or something else. Try going through disabling each extension until you find out the one that's causing the issue.

**Comment by NaturalHarmonia** [comment]
> The first issue can be ignored, chrome is just lying to you as it still works. The second may be some form of adblocker or something else. Try going through disabling each extension until you find out the one that's causing the issue.

Disabled every other extension and it still doesn't work. By the way I'm using Chrome Version 73.0.3683.103 (Official Build) (32-bit) on Windows 10.

**Comment by rtm516** [comment]
I did not find a solution to this issue but I have started a rewrite to this extension if you would like to contribute or test it please check out the rebuild branch. https://github.com/rtm516/Bookmark-Manager/tree/rebuild
