### ISSUE TITLE
after update chrome 74.0.3729.108  its not working anymore

### ISSUE THREAD

**Issue by Hashim-mansoor** [rtm516/Bookmark-Manager#6]
after update chrome 74.0.3729.108  its not working anymore

**Comment by rtm516** [comment]
I've had a look at this issue, I can't pinpoint the exact issue, but its something in the chrome API, as its broken between 73.0.3683.103 and 74.0.3729.108

**Comment by Hashim-mansoor** [comment]
in developer mode (bookmark manager) extension was using the key of live (bookmark manager) extension on webstore
Yesterday chrome have removed extension from webstore so now game over :)

**Comment by rtm516** [comment]
That doesn't seem to be an issue, as running the extension on an older version of chrome still works fine.

**Comment by NaturalHarmonia** [comment]
> That doesn't seem to be an issue, as running the extension on an older version of chrome still works fine.

So that was the issue all along? It was because we were using a recent version of Chrome?

**Comment by rtm516** [comment]
In the new version of chrome, it just hangs at loading the bookmarks page

**Comment by NaturalHarmonia** [comment]
> In the new version of chrome, it just hangs at loading the bookmarks page

Would you be willing to make a fork or something of this? Also what latest version of chrome are you running that this extension works on?

**Comment by rtm516** [comment]
> > In the new version of chrome, it just hangs at loading the bookmarks page
> 
> Would you be willing to make a fork or something of this? Also what latest version of chrome are you running that this extension works on?

I was going to rewrite it, and I'm unsure on which version is the latest it works on as I only have one other machine with chrome installed and that has 73.0.3683.103

**Comment by NaturalHarmonia** [comment]
> > > In the new version of chrome, it just hangs at loading the bookmarks page
> > 
> > 
> > Would you be willing to make a fork or something of this? Also what latest version of chrome are you running that this extension works on?
> 
> I was going to rewrite it, and I'm unsure on which version is the latest it works on as I only have one other machine with chrome installed and that has 73.0.3683.103

Okay, I hope rewriting it doesn't take too long. Best of luck.

**Comment by NoAvalon** [comment]
> > > In the new version of chrome, it just hangs at loading the bookmarks page
> > 
> > 
> > Would you be willing to make a fork or something of this? Also what latest version of chrome are you running that this extension works on?
> 
> I was going to rewrite it, and I'm unsure on which version is the latest it works on as I only have one other machine with chrome installed and that has 73.0.3683.103

Are you considering adding some things to it as well or just leave it as is? When I noticed the extension wasn't working anymore I was looking into a different browser and found opera's bookmark manager to be great. It's basically the same as this extension only that besides choosing an image from the website to be the thumbnail it adds the ability to crop a thumbnail from the whole website as well (nice for youtube bookmarks or websites that don't really have many images) and of course, it has a dark mode.

I'm just really glad that you're not abandoning it. Thank you so much for doing this!

**Comment by rtm516** [comment]
I have started a rewrite to this extension if you would like to contribute or test it please check out the rebuild branch. https://github.com/rtm516/Bookmark-Manager/tree/rebuild
